adapted cloudformation.yml, Dockerfile and buildspec.yml to remove unnecessary docker pulls

diff --git a/cloudformation.yml b/cloudformation.yml
--- a/cloudformation.yml
+++ b/cloudformation.yml
@@ -3,6 +3,21 @@ Parameters:
     Type: String
     Default: "latest"
 
+  RepositoryName:
+    Type: String
+    Default: "alex_it_infra_project"
+
+  VpcId:
+    Type: AWS::EC2::VPC::Id
+
+  PublicSubnets:
+    Type: List<AWS::EC2::Subnet::Id>
+    Description: Public subnets for the ALB (min. two, different AZs)
+
+  AppSubnets:
+    Type: List<AWS::EC2::Subnet::Id>
+    Description: Subnets for the AutoScalingGroup instances
+
 Resources:
   AlexBLaunchConfiguration:
     Type: AWS::AutoScaling::LaunchConfiguration
@@ -15,29 +30,46 @@ Resources:
       UserData:
         Fn::Base64: !Sub |
           #!/bin/bash
+          set -e
+
           echo "Updating system packages..."
           yum update -y
+
           echo "Installing Docker..."
-          dnf install docker -y
+          yum install -y docker
+
           echo "Starting Docker..."
+          systemctl enable docker
           systemctl start docker
+
           echo "Adding ec2-user to Docker group..."
           usermod -a -G docker ec2-user
 
           echo "Logging into Amazon ECR..."
-          $(aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 228383006049.dkr.ecr.eu-west-1.amazonaws.com)
+          aws ecr get-login-password --region ${AWS::Region} | \
+            docker login --username AWS --password-stdin \
+            ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
 
-          echo "Pulling the latest Docker image..."
-          docker pull --quiet --disable-content-trust=true 228383006049.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}
+          IMAGE="${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:${InstanceVersion}"
 
-          echo "Stopping any running containers..."
-          docker stop $(docker ps -q --filter ancestor=228383006049.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}) || true
+          echo "Ensuring image is available locally..."
+          if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
+            echo "Image not found locally. Pulling $IMAGE..."
+            docker pull "$IMAGE"
+          else
+            echo "Image already present locally. Skipping pull."
+          fi
 
-          echo "Removing the old Docker image..."
-          docker rmi 228383006049.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion} || true
+          echo "Stopping existing container if present..."
+          docker stop app || true
+          docker rm app || true
 
-          echo "Running the new Docker container..."
-          docker run -d -p 80:8080 --rm 228383006049.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}
+          echo "Running container..."
+          docker run -d \
+            --name app \
+            -p 80:8080 \
+            --restart unless-stopped \
+            "$IMAGE"
 
   AlexBAutoScalingGroup:
     Type: AWS::AutoScaling::AutoScalingGroup
@@ -46,7 +78,7 @@ Resources:
       MinSize: 1
       MaxSize: 3
       DesiredCapacity: 2
-      AvailabilityZones: !GetAZs ''
+      VPCZoneIdentifier: !Ref AppSubnets
       TargetGroupARNs:
         - !Ref AlexBTargetGroup
       Tags:
@@ -57,16 +89,13 @@ Resources:
 
   AlexBLoadBalancer:
     Type: AWS::ElasticLoadBalancingV2::LoadBalancer
-    DependsOn: AlexBSecurityGroup
     Properties:
       Name: AlexBLoadBalancer
       Scheme: internet-facing
       Type: application
       SecurityGroups:
         - !Ref AlexBSecurityGroup
-      Subnets: 
-        - subnet-08330a0627c9fca46
-        - subnet-0baed77522e17f90c
+      Subnets: !Ref PublicSubnets
       Tags:
         - Key: Name
           Value: AlexBLoadBalancer
@@ -78,7 +107,7 @@ Resources:
       Protocol: HTTP
       Port: 80
       TargetType: instance
-      VpcId: 'vpc-07df1cdc40754775b'
+      VpcId: !Ref VpcId
       HealthCheckEnabled: true
 
   AlexBListener:
@@ -95,7 +124,7 @@ Resources:
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupDescription: Enable HTTP access
-      VpcId: 'vpc-07df1cdc40754775b'
+      VpcId: !Ref VpcId
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: 80
@@ -125,7 +154,12 @@ Resources:
             Statement:
               - Effect: Allow
                 Action:
+                  - ecr:GetAuthorizationToken
+                Resource: "*"
+              - Effect: Allow
+                Action:
+                  - ecr:BatchCheckLayerAvailability
                   - ecr:GetDownloadUrlForLayer
                   - ecr:BatchGetImage
-                  - ecr:GetAuthorizationToken
+                  - ecr:DescribeImages
                 Resource: "*"
